<?
/* Directory Structure
/home/www/acidlife.com/www/subconscio/sub1.html
/home/www/acidlife.com/www/subconscio/sub2.html
/home/www/acidlife.com/www/subconscio/sub3.html
/home/www/acidlife.com/www/subconscio/sub4.html
/home/www/acidlife.com/www/subconscio/sub5.html
/home/www/acidlife.com/www/subconscio/sub6.html
/home/www/acidlife.com/www/subconscio/sub7.html
/home/www/acidlife.com/www/subconscio/sub8.html
/home/www/acidlife.com/www/subconscio/sub9.html
/home/www/acidlife.com/www/subconscio/sub10.html
/home/www/acidlife.com/www/subconscio/sub11.html
/home/www/acidlife.com/www/subconscio/sub12.html
/home/www/acidlife.com/www/subconscio/sub13.html
/home/www/acidlife.com/www/subconscio/sub14.html
/home/www/acidlife.com/www/subconscio/sub15.html
/home/www/acidlife.com/www/subconscio/sub16.html
/home/www/acidlife.com/www/subconscio/sub16.html
/home/www/acidlife.com/www/subconscio/sub18.html
/home/www/acidlife.com/www/subconscio/sub19.html
/home/www/acidlife.com/www/subconscio/sub20.html
/home/www/acidlife.com/www/subconscio/sub21.html
/home/www/acidlife.com/www/subconscio/sub22.html
/home/www/acidlife.com/www/subconscio/sub23.html
/home/www/acidlife.com/www/subconscio/sub24.html
/home/www/acidlife.com/www/subconscio/sub25.html
/home/www/acidlife.com/www/subconscio/sub26.html
/home/www/acidlife.com/www/subconscio/sub27.html
/home/www/acidlife.com/www/subconscio/sub28.html
/home/www/acidlife.com/www/subconscio/sub29.html
/home/www/acidlife.com/www/subconscio/sub30.html
/home/www/acidlife.com/www/subconscio/sub31.html
/home/www/acidlife.com/www/subconscio/sub32.html
/home/www/acidlife.com/www/subconscio/sub33.html
/home/www/acidlife.com/www/subconscio/sub34.html
/home/www/acidlife.com/www/subconscio/sub35.html
/home/www/acidlife.com/www/subconscio/sub36.html
/home/www/acidlife.com/www/subconscio/sub37.html
/home/www/acidlife.com/www/subconscio/sub38.html
/home/www/acidlife.com/www/subconscio/sub39.html
/home/www/acidlife.com/www/subconscio/sub40.html
/home/www/acidlife.com/www/subconscio/sub41.html
/home/www/acidlife.com/www/subconscio/sub43.html
/home/www/acidlife.com/www/subconscio/sub44.html
/home/www/acidlife.com/www/subconscio/sub45.html
/home/www/acidlife.com/www/subconscio/sub46.html
/home/www/acidlife.com/www/subconscio/sub47.html
/home/www/acidlife.com/www/subconscio/sub48.html
/home/www/acidlife.com/www/subconscio/sub49.html
/home/www/acidlife.com/www/subconscio/sub50.html
/home/www/acidlife.com/www/subconscio/sub51.html
*/
srand((double)microtime()*1000000); 
$num = rand(1,51);

include ('/home/www/acidlife.com/www/subconscio/sub'.$num.'.html');

?>